import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {inspectLegacyService,checkLegacyService,retireLegacyService,restoreLegacyService} from '../src/legacy-service.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'legacy-service-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const label='test.legacy-bridge',plist=path.join(root,'Library/LaunchAgents',label+'.plist'),backup=path.join(root,'private/original.plist');fs.mkdirSync(path.dirname(plist),{recursive:true});fs.writeFileSync(plist,'original test property list');let loaded=true,fail=false;const calls=[];const doc={Label:label,ProgramArguments:['/node','/bridge/bridge.mjs','serve'],EnvironmentVariables:{BRIDGE_MODE:'native-tools',BRIDGE_STATE_DIR:path.join(root,'state'),BRIDGE_MODELS:'opencode/big-pickle',BRIDGE_PORT:'4396',OPENCODE_PORT:'4397'}};
 const options={home:root,uid:501,platform:'darwin',run:(cmd,args)=>{calls.push([cmd,args]);if(cmd==='/usr/bin/plutil')return {status:0,stdout:JSON.stringify(doc)};if(args[0]==='print')return {status:loaded?0:113,stdout:loaded?'state = running':''};if(args[0]==='bootout'){if(fail)return {status:1};loaded=false;return {status:0};}if(args[0]==='bootstrap'){loaded=true;return {status:0};}throw Error('unexpected command');}};
 return {root,plist,backup,doc,options,calls,loaded:()=>loaded,fail:()=>{fail=true;}};}
test('Legacy service retirement and restoration preserve exact plist and are repeatable',async t=>{const f=fixture(t),snapshot=inspectLegacyService(f.plist,f.options),bytes=fs.readFileSync(f.plist);assert.equal(snapshot.port,4396);assert.equal(retireLegacyService(snapshot,{...f.options,backup:f.backup}).retired,true);assert.equal(f.loaded(),false);assert.equal(fs.existsSync(f.plist),false);assert.deepEqual(fs.readFileSync(f.backup),bytes);assert.equal(fs.statSync(f.backup).mode&0o777,0o600);retireLegacyService(snapshot,{...f.options,backup:f.backup});await restoreLegacyService(snapshot,{...f.options,backup:f.backup});assert.equal(f.loaded(),true);assert.deepEqual(fs.readFileSync(f.plist),bytes);await restoreLegacyService(snapshot,{...f.options,backup:f.backup});});
test('Edited service, unexpected identity and failed stop remain protected',t=>{const f=fixture(t),snapshot=inspectLegacyService(f.plist,f.options);f.fail();assert.throws(()=>retireLegacyService(snapshot,{...f.options,backup:f.backup}),/Could not stop/);assert.ok(fs.existsSync(f.plist));fs.appendFileSync(f.plist,' edited');assert.throws(()=>retireLegacyService(snapshot,{...f.options,backup:f.backup}),/configuration changed/);f.doc.Label='other.service';assert.throws(()=>inspectLegacyService(f.plist,f.options),/identity/);});
test('Legacy service inspection rejects environment tokens, unsupported commands and symlinks',t=>{const f=fixture(t);f.doc.EnvironmentVariables.BRIDGE_TOKEN='never-display';assert.throws(()=>inspectLegacyService(f.plist,f.options),/protected state file/);delete f.doc.EnvironmentVariables.BRIDGE_TOKEN;f.doc.ProgramArguments[2]='serve-prepared';assert.throws(()=>inspectLegacyService(f.plist,f.options),/explicit legacy/);fs.renameSync(f.plist,f.plist+'.saved');fs.symlinkSync(f.plist+'.saved',f.plist);assert.throws(()=>inspectLegacyService(f.plist,f.options),/regular file/);});
test('Legacy health requires native mode and zero active requests before cutover',async()=>{for(const health of [{ok:true,mode:'text',active:0},{ok:true,mode:'native-tools',active:1},{ok:false,mode:'native-tools',active:0}])await assert.rejects(checkLegacyService({port:4396},{fetchImpl:async()=>({ok:true,json:async()=>health})}),/unavailable, incompatible or busy/);assert.equal((await checkLegacyService({port:4396},{fetchImpl:async()=>({ok:true,json:async()=>({ok:true,mode:'native-tools',active:0})})})).idle,true);});
test('Restored legacy health waits for startup rather than treating launch acknowledgement as readiness',async()=>{
 const {waitLegacyService}=await import('../src/legacy-service.mjs');let calls=0;assert.equal((await waitLegacyService({port:4396},{check:async()=>{if(++calls<3)throw Error('not listening yet');return {healthy:true};},delay:async()=>{},attempts:3})).healthy,true);assert.equal(calls,3);
 await assert.rejects(waitLegacyService({port:4396},{check:async()=>{throw Error('failed startup');},delay:async()=>{},attempts:2}),/did not become healthy/);
});
